### ISSUE TITLE
能否把示例model.plan也上传网盘？

### ISSUE THREAD

**Issue by WQ-2001-mc** [emptysoal/YOLOv5-TensorRT-lib-Python#1]
这样会给使用者带来极大便利，谢谢

**Comment by emptysoal** [comment]
首先非常荣幸你对我的项目感兴趣，当时发布的时候我也考虑要不要把TensorRT转换后的模型放到网盘链接里，但是TensorRT对GPU硬件、CUDA版本、TensorRT自身版本等极度敏感，只有高度一致情况下，model.plan文件才能复用，所以绝大多数情况下还是需要自己做转换的，因此我也就没有放到网盘上
